### ISSUE TITLE
Error when trying to select files

### ISSUE THREAD

**Issue by AbbyKimball** [akoyabio/phenoptrReports#8]
Hello! I'm having an issue with the shinyapp, when I try to import my files it crashes and I am given this error:

```
Listening on http://127.0.0.1:4644
Warning: Error in : 'choose.dir' is not an exported object from 'namespace:utils'
  79: stop
  78: getExportedValue
  77: ::
  74: observeEventHandler
   3: shiny::runApp
   2: shiny::runGadget
   1: phenoptrReports:::addin_10_merge
```

Thanks!

**Comment by AB-Kent** [comment]
I see that choose.dir() is Windows-specific. Are you running on Windows?

**Comment by AbbyKimball** [comment]
Nope, I am doing this on a mac. Please note that I didn't run the command 'choose.dir' this is just the error I get after the shinyapp crashes. For example, I select "Addins > Merge inForm Data" and then the pop out window appears, I select "browse input" to grab my files of interest and then the popout crashes the error above appears.

**Comment by AB-Kent** [comment]
choose.dir() is used by the addin. I didn't realize it was Windows-specific. I need to replace both choose.dir() and choose.files() :-/

**Comment by AbbyKimball** [comment]
Let me know when you think it will be working! I'm almost done putting together a manuscript and I'd love to add something about phenoptrReports! Thanks!

**Comment by AB-Kent** [comment]
Should be fixed now in the development build. To use it, you will also need the dev build of `phenoptr`. Install both with
```
devtools::install_github('akoyabio/phenoptr@9000')
devtools::install_github('akoyabio/phenoptrReports@9000')
```

Let me know if it works, I don't have a Mac to test on.

**Comment by AbbyKimball** [comment]
Fantastic! So now the Addin "merge cell seg files" works perfectly well, but I am still getting the same error when I try the other Addin options (ex: consolidate and summarize). 

Whatever you did worked it just seems like it has to be applied for all functions.

Thanks!

**Comment by AB-Kent** [comment]
Can you try restarting RStudio? I did change the other addins. If that doesn't work, please post the complete error message. Thanks!

**Comment by AbbyKimball** [comment]
I just tried restarting and I'm still having the issue with the "consolidate and summarize" option.

Here is the error :)

`Listening on http://127.0.0.1:3113
Warning: Error in : 'Filters' is not an exported object from 'namespace:utils'
  79: stop
  78: getExportedValue
  77: ::
  74: observeEventHandler
   3: shiny::runApp
   2: shiny::runGadget
   1: phenoptrReports:::addin_20_consolidate`

Thank you!

**Comment by AB-Kent** [comment]
Please re-install `phenoptrReports` and try again.
`devtools::install_github('akoyabio/phenoptrReports@9000')`

**Comment by AB-Kent** [comment]
@AbbyKimball Is this fixed for you now?

**Comment by jpo-costa** [comment]
I have the same error and I did install devtools::install_github('akoyabio/phenoptrReports@9000')
